name: 'Test action'

on:
  push:
    tags: '*'
    branches-ignore:
      - 'autodelivery**'
      - 'bump-**'
      - 'renovate/**'
    paths-ignore:
      - 'README.md'
      - 'CHANGELOG.md'
      - 'LICENSE'
      - 'renovate.json'
  pull_request:
  workflow_dispatch:

jobs:
  base-test:
    runs-on: ubuntu-latest
    name: Base test
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3.2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Test
        run: ./test.sh
